version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always

  # TODO: Dockerize
  # messageprocessor: {}
  # reportingapi: {}

  api:
    image: catbyte/api
    build:
      context: .
      dockerfile: go.Dockerfile
      args:
        APP: api
    ports:
      - "9000:9000"
    environment:
      - ADDR=:9000
      - AMQP_URL=amqp://user:password@rabbitmq:5672/

  messageprocessor:
    image: catbyte/messageprocessor
    build:
      context: .
      dockerfile: go.Dockerfile
      args:
        APP: messageprocessor
    environment:
      - AMQP_URL=amqp://user:password@rabbitmq:5672/
      - REDIS_ADDR=redis:6379

  reportingapi:
    image: catbyte/reportingapi
    build:
      context: .
      dockerfile: go.Dockerfile
      args:
        APP: reportingapi
    ports:
      - "9001:9001"
    environment:
      - ADDR=:9001
      - REDIS_ADDR=redis:6379
